version: '3.8'
services:
  postgres-hibernate:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=hibernate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 2